'use client';

import { zodResolver } from '@hookform/resolvers/zod';
import { ChevronLeft, ChevronRight, Download, Pencil, Plus, Trash2, Upload, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useFieldArray, useForm } from 'react-hook-form';
import { z } from 'zod';
import { useAuth } from '@/components/auth-provider';
import { DataTable, type DataTableColumn } from '@/components/data-table';
import { EmptyState } from '@/components/empty-state';
import { ErrorState, PermissionDeniedState } from '@/components/error-state';
import { FilterBar } from '@/components/filter-bar';
import { LoadingState } from '@/components/loading-state';
import { PageHeader } from '@/components/page-header';
import { StatusBadge } from '@/components/status-badge';

type RateStatus = 'DRAFT' | 'ACTIVE' | 'EXPIRED' | 'INACTIVE';
type ChargeBasis = 'PER_CONTAINER' | 'PER_BL' | 'PER_SHIPMENT';
interface RatePrice { id: string; containerType: string; costAmount: string; sellAmount: string | null; currency: string; remark: string | null }
interface RateCharge { id: string; chargeCode: string; chargeName: string; chargeBasis: ChargeBasis; containerType: string | null; amount: string; currency: string; isIncluded: boolean }
interface Rate {
  id: string; rateNo: string; polCode: string; polName: string; podCode: string; podName: string;
  carrierCode: string; serviceName: string | null; effectiveDate: string; expiryDate: string;
  etd: string | null; transitDays: number | null; supplierName: string | null; contractNo: string | null;
  currency: string; status: RateStatus; prices: RatePrice[]; charges: RateCharge[]; updatedAt: string;
}
interface RateListResponse { items: Rate[]; pagination: { page: number; pageSize: number; total: number; totalPages: number } }
interface RateImport { id: string; originalFileName: string; status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED'; totalRows: number; successRows: number; failedRows: number; errors: Array<{ row: number; field: string; message: string }> | null; errorMessage: string | null; createdAt: string }
interface ApiErrorPayload { code?: string; message?: string }
class RateApiError extends Error { constructor(message: string, readonly code?: string) { super(message); } }

const decimal = z.string().trim().regex(/^\d{1,14}(?:\.\d{1,4})?$/, '请输入非负金额，最多 4 位小数');
const optionalDecimal = z.string().trim().refine((value) => !value || /^\d{1,14}(?:\.\d{1,4})?$/.test(value), '请输入非负金额，最多 4 位小数');
const rateFormSchema = z.object({
  rateNo: z.string().trim().min(1, '运价编号为必填项').max(50).regex(/^[A-Za-z0-9][A-Za-z0-9_-]*$/, '仅支持字母、数字、下划线和连字符'),
  polCode: z.string().trim().min(3, '请输入起运港代码').max(10).regex(/^[A-Za-z0-9]+$/, '仅支持字母和数字'),
  polName: z.string().trim().min(1, '起运港名称为必填项').max(150),
  podCode: z.string().trim().min(3, '请输入目的港代码').max(10).regex(/^[A-Za-z0-9]+$/, '仅支持字母和数字'),
  podName: z.string().trim().min(1, '目的港名称为必填项').max(150),
  carrierCode: z.string().trim().min(2, '船司代码为必填项').max(20).regex(/^[A-Za-z0-9]+$/, '仅支持字母和数字'),
  serviceName: z.string().trim().max(150), effectiveDate: z.string().min(1, '生效日为必填项'), expiryDate: z.string().min(1, '失效日为必填项'),
  etd: z.string(), transitDays: z.string().trim().refine((value) => !value || (/^\d+$/.test(value) && Number(value) <= 365), '请输入 0–365 的整数'),
  supplierName: z.string().trim().max(200), contractNo: z.string().trim().max(100),
  currency: z.string().trim().regex(/^[A-Za-z]{3}$/, '请输入三位币种代码'), status: z.enum(['DRAFT', 'ACTIVE', 'EXPIRED', 'INACTIVE']),
  prices: z.array(z.object({ containerType: z.string().min(1, '请选择箱型'), costAmount: decimal, sellAmount: optionalDecimal, currency: z.string().regex(/^[A-Za-z]{3}$/, '三位币种代码'), remark: z.string().max(500) })).min(1, '至少添加一个箱型价格'),
  charges: z.array(z.object({ chargeCode: z.string().trim().min(1, '费用代码为必填项').max(30).regex(/^[A-Za-z0-9_-]+$/, '费用代码格式不正确'), chargeName: z.string().trim().min(1, '费用名称为必填项').max(150), chargeBasis: z.enum(['PER_CONTAINER', 'PER_BL', 'PER_SHIPMENT']), containerType: z.string(), amount: decimal, currency: z.string().regex(/^[A-Za-z]{3}$/, '三位币种代码'), isIncluded: z.boolean() })),
}).superRefine((value, context) => {
  if (value.effectiveDate && value.expiryDate && value.effectiveDate > value.expiryDate) context.addIssue({ code: z.ZodIssueCode.custom, path: ['expiryDate'], message: '失效日不能早于生效日' });
  const types = value.prices.map((price) => price.containerType);
  if (new Set(types).size !== types.length) context.addIssue({ code: z.ZodIssueCode.custom, path: ['prices'], message: '同一箱型只能添加一次' });
  value.charges.forEach((charge, index) => {
    if (charge.chargeBasis === 'PER_CONTAINER' && !charge.containerType) context.addIssue({ code: z.ZodIssueCode.custom, path: ['charges', index, 'containerType'], message: '按箱费用必须选择箱型' });
  });
});
type RateFormValues = z.infer<typeof rateFormSchema>;

const statusLabels: Record<RateStatus, string> = { DRAFT: '草稿', ACTIVE: '启用', EXPIRED: '已过期', INACTIVE: '停用' };
const statusTones = { DRAFT: 'neutral', ACTIVE: 'success', EXPIRED: 'warning', INACTIVE: 'neutral' } as const;
const basisLabels: Record<ChargeBasis, string> = { PER_CONTAINER: '按箱', PER_BL: '按提单', PER_SHIPMENT: '按票' };
const containerTypes = ['20GP', '40GP', '40HQ', '45HQ'];

export default function RatesPage() {
  const { apiFetch, user } = useAuth();
  const [items, setItems] = useState<Rate[]>([]);
  const [pagination, setPagination] = useState<RateListResponse['pagination']>({ page: 1, pageSize: 20, total: 0, totalPages: 0 });
  const [page, setPage] = useState(1); const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState('');
  const [status, setStatus] = useState<RateStatus | ''>(''); const [polCode, setPolCode] = useState(''); const [podCode, setPodCode] = useState(''); const [carrierCode, setCarrierCode] = useState(''); const [containerType, setContainerType] = useState(''); const [validOn, setValidOn] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState<RateApiError | null>(null); const [reloadKey, setReloadKey] = useState(0);
  const [dialogOpen, setDialogOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [editingRate, setEditingRate] = useState<Rate | null>(null); const [notice, setNotice] = useState<string | null>(null);

  useEffect(() => { const timer = window.setTimeout(() => { setPage(1); setSearch(searchInput.trim()); }, 300); return () => window.clearTimeout(timer); }, [searchInput]);
  const load = useCallback(async () => {
    setLoading(true); setError(null);
    const query = new URLSearchParams({ page: String(page), pageSize: '20' });
    if (search) query.set('search', search); if (status) query.set('status', status); if (polCode) query.set('polCode', polCode.trim().toUpperCase()); if (podCode) query.set('podCode', podCode.trim().toUpperCase()); if (carrierCode) query.set('carrierCode', carrierCode.trim().toUpperCase()); if (containerType) query.set('containerType', containerType); if (validOn) query.set('validOn', validOn);
    try { const result = await requestJson<RateListResponse>(apiFetch, `/api/v1/rates?${query.toString()}`); setItems(result.items); setPagination(result.pagination); }
    catch (caught) { setError(toRateError(caught)); } finally { setLoading(false); }
  }, [apiFetch, carrierCode, containerType, page, podCode, polCode, search, status, validOn]);
  useEffect(() => { void load(); }, [load, reloadKey]);
  const canManage = user?.roles.some((role) => ['SUPER_ADMIN', 'TENANT_ADMIN'].includes(role));
  const columns = useMemo<DataTableColumn<Rate>[]>(() => [
    { key: 'rateNo', header: 'Rate', render: (rate) => <div><div className="font-medium">{rate.rateNo}</div><div className="mt-0.5 text-xs text-muted">{rate.serviceName ?? '未设置服务'}</div></div> },
    { key: 'route', header: '航线', render: (rate) => <div><div>{rate.polCode} → {rate.podCode}</div><div className="mt-0.5 text-xs text-muted">{rate.polName} → {rate.podName}</div></div> },
    { key: 'carrierCode', header: '船司', render: (rate) => rate.carrierCode },
    { key: 'prices', header: '箱型 / 成本', render: (rate) => <div className="space-y-1">{rate.prices.map((price) => <div key={price.id} className="whitespace-nowrap"><span className="inline-block w-12 text-xs text-muted">{price.containerType}</span> {formatMoney(price.costAmount, price.currency)}</div>)}</div> },
    { key: 'validity', header: '有效期', render: (rate) => <div className="whitespace-nowrap">{formatDate(rate.effectiveDate)}<div className="mt-0.5 text-xs text-muted">至 {formatDate(rate.expiryDate)}</div></div> },
    { key: 'supplierName', header: '供应方 / 合约', render: (rate) => <div>{rate.supplierName ?? '—'}<div className="mt-0.5 text-xs text-muted">{rate.contractNo ?? '无合约号'}</div></div> },
    { key: 'status', header: '状态', render: (rate) => <StatusBadge tone={statusTones[rate.status]}>{statusLabels[rate.status]}</StatusBadge> },
    ...(canManage ? [{ key: 'actions', header: '操作', className: 'w-[108px] min-w-[108px] whitespace-nowrap text-right', render: (rate: Rate) => <button aria-label={`编辑运价 ${rate.rateNo}`} className="inline-flex h-8 shrink-0 items-center justify-center gap-1.5 whitespace-nowrap rounded-md border border-border bg-surface px-3.5 text-sm font-medium shadow-sm transition-colors hover:border-primary hover:bg-primary/5 hover:text-primary focus:outline-none focus:ring-2 focus:ring-primary/20" onClick={() => setEditingRate(rate)} type="button"><Pencil aria-hidden className="size-3.5 shrink-0" /> <span>编辑</span></button> }] : []),
  ], [canManage]);
  const clearFilters = () => { setSearchInput(''); setSearch(''); setStatus(''); setPolCode(''); setPodCode(''); setCarrierCode(''); setContainerType(''); setValidOn(''); setPage(1); };
  const saved = (editing: boolean) => { setDialogOpen(false); setEditingRate(null); setNotice(editing ? '运价已更新，修改记录已写入审计日志。' : '运价创建成功。'); setPage(1); setReloadKey((value) => value + 1); };

  return <div className="space-y-5">
    <PageHeader actions={canManage ? <div className="flex items-center gap-2"><button className="inline-flex h-9 items-center gap-2 rounded border border-border bg-surface px-4 text-sm font-semibold hover:border-primary hover:text-primary" onClick={() => setImportOpen(true)} type="button"><Upload aria-hidden className="size-4" /> Excel 导入</button><button className="inline-flex h-9 items-center gap-2 rounded bg-primary px-4 text-sm font-semibold text-surface" onClick={() => setDialogOpen(true)} type="button"><Plus aria-hidden className="size-4" /> 新建运价</button></div> : undefined} description="维护航线、船司、有效期、箱型成本和附加费用。" eyebrow="运营后台" title="运价" />
    {notice ? <div className="flex items-center justify-between rounded border border-success/20 bg-success/10 px-4 py-3 text-sm text-success"><span>{notice}</span><button aria-label="关闭提示" onClick={() => setNotice(null)} type="button"><X aria-hidden className="size-4" /></button></div> : null}
    {error?.code === 'PERMISSION_DENIED' ? <PermissionDeniedState /> : <section className="overflow-hidden rounded border border-border bg-surface">
      <FilterBar onClear={clearFilters} onSearchChange={setSearchInput} placeholder="搜索运价编号、港口、供应方或合约号" searchValue={searchInput}>
        <input aria-label="起运港代码" className={filterClass} onChange={(event) => { setPolCode(event.target.value); setPage(1); }} placeholder="POL" value={polCode} />
        <input aria-label="目的港代码" className={filterClass} onChange={(event) => { setPodCode(event.target.value); setPage(1); }} placeholder="POD" value={podCode} />
        <input aria-label="船司代码" className={filterClass} onChange={(event) => { setCarrierCode(event.target.value); setPage(1); }} placeholder="Carrier" value={carrierCode} />
        <select aria-label="箱型" className={filterClass} onChange={(event) => { setContainerType(event.target.value); setPage(1); }} value={containerType}><option value="">全部箱型</option>{containerTypes.map((type) => <option key={type}>{type}</option>)}</select>
        <select aria-label="运价状态" className={filterClass} onChange={(event) => { setStatus(event.target.value as RateStatus | ''); setPage(1); }} value={status}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>
        <label className="flex items-center gap-2 text-xs text-muted">有效日<input aria-label="有效日" className={filterClass} onChange={(event) => { setValidOn(event.target.value); setPage(1); }} type="date" value={validOn} /></label>
      </FilterBar>
      {loading ? <LoadingState rows={6} /> : error ? <div className="p-4"><ErrorState description={error.message} onRetry={() => setReloadKey((value) => value + 1)} /></div> : items.length === 0 ? <div className="p-4"><EmptyState description={search || status || polCode || podCode || carrierCode || containerType || validOn ? '请调整筛选条件后重试。' : '新建运价后，记录会显示在这里。'} title="暂无匹配运价" /></div> : <><DataTable columns={columns} data={items} getRowKey={(rate) => rate.id} /><Pagination page={page} pagination={pagination} setPage={setPage} /></>}
    </section>}
    {dialogOpen || editingRate ? <RateDialog apiFetch={apiFetch} rate={editingRate} onClose={() => { setDialogOpen(false); setEditingRate(null); }} onSaved={() => saved(Boolean(editingRate))} /> : null}
    {importOpen ? <ImportRateDialog apiFetch={apiFetch} onClose={() => setImportOpen(false)} onCompleted={() => { setNotice('Excel 运价导入完成，列表已刷新。'); setPage(1); setReloadKey((value) => value + 1); }} /> : null}
  </div>;
}

function ImportRateDialog({ apiFetch, onClose, onCompleted }: { apiFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>; onClose: () => void; onCompleted: () => void }) {
  const [file, setFile] = useState<File | null>(null); const [importJob, setImportJob] = useState<RateImport | null>(null); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [downloading, setDownloading] = useState(false);
  useEffect(() => {
    if (!importJob || !['PENDING', 'PROCESSING'].includes(importJob.status)) return;
    const timer = window.setInterval(() => { void requestJson<RateImport>(apiFetch, `/api/v1/rate-imports/${importJob.id}`).then((result) => { setImportJob(result); if (result.status === 'COMPLETED') { window.clearInterval(timer); onCompleted(); } }).catch((caught) => { window.clearInterval(timer); setError(toRateError(caught).message); }); }, 1000);
    return () => window.clearInterval(timer);
  }, [apiFetch, importJob, onCompleted]);
  const upload = async () => { if (!file) { setError('请选择 .xlsx 文件。'); return; } setSubmitting(true); setError(null); const form = new FormData(); form.append('file', file); try { setImportJob(await requestJson<RateImport>(apiFetch, '/api/v1/rates/import', { method: 'POST', body: form })); } catch (caught) { setError(toRateError(caught).message); } finally { setSubmitting(false); } };
  const downloadTemplate = async () => { setDownloading(true); setError(null); try { const response = await apiFetch('/api/v1/rates/import-template'); if (!response.ok) throw new RateApiError('模板下载失败，请稍后重试。'); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'rate-import-template.xlsx'; anchor.click(); URL.revokeObjectURL(url); } catch (caught) { setError(toRateError(caught).message); } finally { setDownloading(false); } };
  const busy = submitting || importJob?.status === 'PENDING' || importJob?.status === 'PROCESSING';
  return <div aria-labelledby="import-rate-title" aria-modal="true" className="fixed inset-0 z-50 flex items-start justify-end bg-foreground/30" role="dialog"><button aria-label="关闭导入表单" className="absolute inset-0" disabled={busy} onClick={onClose} type="button" /><div className="relative h-full w-full max-w-2xl overflow-y-auto border-l border-border bg-surface shadow-xl"><div className="flex items-start justify-between border-b border-border px-5 py-4"><div><h2 className="text-lg font-semibold" id="import-rate-title">Excel 导入运价</h2><p className="mt-1 text-sm text-muted">使用标准模板；整批校验通过后才会写入数据库。</p></div><button aria-label="关闭" className="grid size-9 place-items-center rounded border border-border disabled:opacity-40" disabled={busy} onClick={onClose} type="button"><X className="size-4" /></button></div><div className="space-y-5 p-5">
    <section className="rounded border border-border bg-background p-4"><h3 className="text-sm font-semibold">1. 下载并填写模板</h3><p className="mt-1 text-sm text-muted">一行代表一个箱型价格；相同 rateNo 的多行会合并为一条运价。</p><button className={`${secondaryButton} mt-3`} disabled={downloading || busy} onClick={() => void downloadTemplate()} type="button"><Download className="size-3.5" /> {downloading ? '下载中…' : '下载标准模板'}</button></section>
    <section className="rounded border border-border bg-background p-4"><h3 className="text-sm font-semibold">2. 上传工作簿</h3><input accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="mt-3 block w-full rounded border border-border bg-surface p-2 text-sm file:mr-3 file:rounded file:border-0 file:bg-sidebar file:px-3 file:py-1.5 file:text-sm file:font-medium" disabled={busy} onChange={(event) => { setFile(event.target.files?.[0] ?? null); setError(null); setImportJob(null); }} type="file" /><p className="mt-2 text-xs text-muted">仅支持 .xlsx，最大 5 MB、最多 5,000 个数据行。已有 rateNo 会导致整批失败。</p></section>
    {error ? <div className="rounded border border-danger/20 bg-danger/10 px-3 py-2 text-sm text-danger">{error}</div> : null}
    {importJob ? <section className={`rounded border p-4 ${importJob.status === 'FAILED' ? 'border-danger/20 bg-danger/5' : importJob.status === 'COMPLETED' ? 'border-success/20 bg-success/5' : 'border-border bg-background'}`}><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">导入结果</h3><StatusBadge tone={importJob.status === 'COMPLETED' ? 'success' : importJob.status === 'FAILED' ? 'danger' : 'info'}>{importJob.status === 'PENDING' ? '等待处理' : importJob.status === 'PROCESSING' ? '正在处理' : importJob.status === 'COMPLETED' ? '导入完成' : '导入失败'}</StatusBadge></div><dl className="mt-3 grid grid-cols-3 gap-3 text-sm"><div><dt className="text-muted">总行数</dt><dd className="mt-1 font-semibold">{importJob.totalRows}</dd></div><div><dt className="text-muted">成功</dt><dd className="mt-1 font-semibold text-success">{importJob.successRows}</dd></div><div><dt className="text-muted">失败</dt><dd className="mt-1 font-semibold text-danger">{importJob.failedRows}</dd></div></dl>{importJob.errorMessage ? <p className="mt-3 text-sm text-danger">{importJob.errorMessage}</p> : null}{importJob.errors?.length ? <div className="mt-3 max-h-64 overflow-auto rounded border border-border bg-surface"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-sidebar"><tr><th className="px-3 py-2">行</th><th className="px-3 py-2">字段</th><th className="px-3 py-2">错误</th></tr></thead><tbody>{importJob.errors.map((item, index) => <tr className="border-t border-border" key={`${item.row}-${item.field}-${index}`}><td className="px-3 py-2">{item.row}</td><td className="px-3 py-2 font-mono">{item.field}</td><td className="px-3 py-2">{item.message}</td></tr>)}</tbody></table></div> : null}</section> : null}
    <div className="flex justify-end gap-2 border-t border-border pt-4"><button className="h-9 rounded border border-border px-4 text-sm font-semibold disabled:opacity-40" disabled={busy} onClick={onClose} type="button">关闭</button><button className="h-9 rounded bg-primary px-4 text-sm font-semibold text-surface disabled:opacity-40" disabled={!file || busy || importJob?.status === 'COMPLETED'} onClick={() => void upload()} type="button">{submitting ? '上传中…' : busy ? '处理中…' : importJob?.status === 'FAILED' ? '重新上传' : '开始导入'}</button></div>
  </div></div></div>;
}

function RateDialog({ apiFetch, rate, onClose, onSaved }: { apiFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>; rate: Rate | null; onClose: () => void; onSaved: () => void }) {
  const [submitError, setSubmitError] = useState<string | null>(null);
  const { register, control, handleSubmit, watch, setValue, formState: { errors, isSubmitting } } = useForm<RateFormValues>({ resolver: zodResolver(rateFormSchema), defaultValues: rate ? rateDefaults(rate) : emptyRateDefaults() });
  const prices = useFieldArray({ control, name: 'prices' }); const charges = useFieldArray({ control, name: 'charges' }); const mainCurrency = watch('currency');
  useEffect(() => { if (!rate) { prices.fields.forEach((_, index) => setValue(`prices.${index}.currency`, mainCurrency.toUpperCase())); charges.fields.forEach((_, index) => setValue(`charges.${index}.currency`, mainCurrency.toUpperCase())); } }, [charges.fields, mainCurrency, prices.fields, rate, setValue]);
  const submit = handleSubmit(async (values) => {
    setSubmitError(null);
    const payload = { ...values, rateNo: upper(values.rateNo), polCode: upper(values.polCode), podCode: upper(values.podCode), carrierCode: upper(values.carrierCode), currency: upper(values.currency), ...(values.etd ? { etd: new Date(values.etd).toISOString() } : { etd: undefined }), ...(values.transitDays ? { transitDays: Number(values.transitDays) } : { transitDays: undefined }), serviceName: optional(values.serviceName), supplierName: optional(values.supplierName), contractNo: optional(values.contractNo), prices: values.prices.map((price) => ({ ...price, containerType: upper(price.containerType), currency: upper(price.currency), remark: optional(price.remark), ...(price.sellAmount ? {} : { sellAmount: undefined }) })), charges: values.charges.map((charge) => ({ ...charge, chargeCode: upper(charge.chargeCode), chargeName: charge.chargeName.trim(), currency: upper(charge.currency), ...(charge.chargeBasis === 'PER_CONTAINER' ? { containerType: charge.containerType } : { containerType: undefined }) })) };
    try { await requestJson<Rate>(apiFetch, rate ? `/api/v1/rates/${rate.id}` : '/api/v1/rates', { method: rate ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); onSaved(); } catch (caught) { setSubmitError(toRateError(caught).message); }
  });
  return <div aria-labelledby="rate-dialog-title" aria-modal="true" className="fixed inset-0 z-50 flex items-start justify-end bg-foreground/30" role="dialog"><button aria-label="关闭运价表单" className="absolute inset-0" onClick={onClose} type="button" /><div className="relative h-full w-full max-w-4xl overflow-y-auto border-l border-border bg-surface shadow-xl">
    <div className="sticky top-0 z-10 flex items-start justify-between border-b border-border bg-surface px-5 py-4"><div><h2 className="text-lg font-semibold" id="rate-dialog-title">{rate ? '编辑运价' : '新建运价'}</h2><p className="mt-1 text-sm text-muted">带 * 的字段为必填项；金额最多保留 4 位小数。</p></div><button aria-label="关闭" className="grid size-9 place-items-center rounded border border-border" onClick={onClose} type="button"><X aria-hidden className="size-4" /></button></div>
    <form className="space-y-6 p-5" onSubmit={(event) => void submit(event)}>{submitError ? <div className="rounded border border-danger/20 bg-danger/10 px-3 py-2 text-sm text-danger">{submitError}</div> : null}
      <fieldset className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><legend className="col-span-full text-sm font-semibold">基础信息</legend>
        <FormField error={errors.rateNo?.message} label="运价编号 *"><input {...register('rateNo')} className={inputClass} /></FormField><FormField error={errors.carrierCode?.message} label="船司代码 *"><input {...register('carrierCode')} className={inputClass} placeholder="COSCO" /></FormField><FormField error={errors.serviceName?.message} label="航线服务"><input {...register('serviceName')} className={inputClass} /></FormField><FormField error={errors.status?.message} label="状态 *"><select {...register('status')} className={inputClass}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></FormField>
        <FormField error={errors.polCode?.message} label="POL 代码 *"><input {...register('polCode')} className={inputClass} placeholder="CNSHA" /></FormField><FormField error={errors.polName?.message} label="POL 名称 *"><input {...register('polName')} className={inputClass} /></FormField><FormField error={errors.podCode?.message} label="POD 代码 *"><input {...register('podCode')} className={inputClass} placeholder="USLAX" /></FormField><FormField error={errors.podName?.message} label="POD 名称 *"><input {...register('podName')} className={inputClass} /></FormField>
        <FormField error={errors.effectiveDate?.message} label="生效日 *"><input {...register('effectiveDate')} className={inputClass} type="date" /></FormField><FormField error={errors.expiryDate?.message} label="失效日 *"><input {...register('expiryDate')} className={inputClass} type="date" /></FormField><FormField error={errors.etd?.message} label="ETD"><input {...register('etd')} className={inputClass} type="datetime-local" /></FormField><FormField error={errors.transitDays?.message} label="航程（天）"><input {...register('transitDays')} className={inputClass} inputMode="numeric" /></FormField>
        <FormField error={errors.supplierName?.message} label="供应方"><input {...register('supplierName')} className={inputClass} /></FormField><FormField error={errors.contractNo?.message} label="合约号"><input {...register('contractNo')} className={inputClass} /></FormField><FormField error={errors.currency?.message} label="基础币种 *"><input {...register('currency')} className={inputClass} maxLength={3} /></FormField>
      </fieldset>
      <fieldset className="space-y-3 border-t border-border pt-5"><div className="flex items-center justify-between"><legend className="text-sm font-semibold">箱型价格 *</legend><button className={secondaryButton} onClick={() => prices.append({ containerType: '40HQ', costAmount: '', sellAmount: '', currency: mainCurrency || 'USD', remark: '' })} type="button"><Plus className="size-3.5" /> 添加箱型</button></div>{errors.prices?.root?.message ? <p className="text-xs text-danger">{errors.prices.root.message}</p> : null}
        {prices.fields.map((field, index) => <div className="grid gap-3 rounded border border-border bg-background p-3 sm:grid-cols-2 lg:grid-cols-[110px_1fr_1fr_100px_1.4fr_40px]" key={field.id}><FormField error={errors.prices?.[index]?.containerType?.message} label="箱型"><select {...register(`prices.${index}.containerType`)} className={inputClass}>{containerTypes.map((type) => <option key={type}>{type}</option>)}</select></FormField><FormField error={errors.prices?.[index]?.costAmount?.message} label="采购成本"><input {...register(`prices.${index}.costAmount`)} className={inputClass} inputMode="decimal" /></FormField><FormField error={errors.prices?.[index]?.sellAmount?.message} label="标准售价"><input {...register(`prices.${index}.sellAmount`)} className={inputClass} inputMode="decimal" /></FormField><FormField error={errors.prices?.[index]?.currency?.message} label="币种"><input {...register(`prices.${index}.currency`)} className={inputClass} maxLength={3} /></FormField><FormField error={errors.prices?.[index]?.remark?.message} label="备注"><input {...register(`prices.${index}.remark`)} className={inputClass} /></FormField><button aria-label="删除箱型价格" className="mt-6 grid size-10 place-items-center rounded border border-border text-muted hover:text-danger disabled:opacity-30" disabled={prices.fields.length === 1} onClick={() => prices.remove(index)} type="button"><Trash2 className="size-4" /></button></div>)}
      </fieldset>
      <fieldset className="space-y-3 border-t border-border pt-5"><div className="flex items-center justify-between"><legend className="text-sm font-semibold">附加费用</legend><button className={secondaryButton} onClick={() => charges.append({ chargeCode: '', chargeName: '', chargeBasis: 'PER_CONTAINER', containerType: '40HQ', amount: '', currency: mainCurrency || 'USD', isIncluded: false })} type="button"><Plus className="size-3.5" /> 添加费用</button></div>
        {charges.fields.length === 0 ? <p className="rounded border border-dashed border-border p-4 text-sm text-muted">暂无附加费用。</p> : charges.fields.map((field, index) => { const basis = watch(`charges.${index}.chargeBasis`); return <div className="grid gap-3 rounded border border-border bg-background p-3 sm:grid-cols-2 lg:grid-cols-[110px_1.3fr_120px_100px_1fr_90px_40px]" key={field.id}><FormField error={errors.charges?.[index]?.chargeCode?.message} label="费用代码"><input {...register(`charges.${index}.chargeCode`)} className={inputClass} /></FormField><FormField error={errors.charges?.[index]?.chargeName?.message} label="费用名称"><input {...register(`charges.${index}.chargeName`)} className={inputClass} /></FormField><FormField error={errors.charges?.[index]?.chargeBasis?.message} label="计价单位"><select {...register(`charges.${index}.chargeBasis`)} className={inputClass}>{Object.entries(basisLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></FormField><FormField error={errors.charges?.[index]?.containerType?.message} label="箱型"><select {...register(`charges.${index}.containerType`)} className={inputClass} disabled={basis !== 'PER_CONTAINER'}><option value="">请选择</option>{containerTypes.map((type) => <option key={type}>{type}</option>)}</select></FormField><FormField error={errors.charges?.[index]?.amount?.message} label="金额"><input {...register(`charges.${index}.amount`)} className={inputClass} inputMode="decimal" /></FormField><FormField error={errors.charges?.[index]?.currency?.message} label="币种"><input {...register(`charges.${index}.currency`)} className={inputClass} maxLength={3} /></FormField><button aria-label="删除附加费用" className="mt-6 grid size-10 place-items-center rounded border border-border text-muted hover:text-danger" onClick={() => charges.remove(index)} type="button"><Trash2 className="size-4" /></button><label className="col-span-full inline-flex items-center gap-2 text-sm"><input {...register(`charges.${index}.isIncluded`)} type="checkbox" /> 已包含在主运价中</label></div>; })}
      </fieldset>
      <div className="sticky bottom-0 flex justify-end gap-2 border-t border-border bg-surface py-4"><button className="h-9 rounded border border-border px-4 text-sm font-semibold" disabled={isSubmitting} onClick={onClose} type="button">取消</button><button className="h-9 rounded bg-primary px-4 text-sm font-semibold text-surface disabled:opacity-50" disabled={isSubmitting} type="submit">{isSubmitting ? '保存中…' : rate ? '保存变更' : '保存运价'}</button></div>
    </form>
  </div></div>;
}

function Pagination({ page, pagination, setPage }: { page: number; pagination: RateListResponse['pagination']; setPage: React.Dispatch<React.SetStateAction<number>> }) { return <div className="flex items-center justify-between border-t border-border px-4 py-3 text-sm text-muted"><span>共 {pagination.total} 条运价</span><div className="flex items-center gap-2"><button aria-label="上一页" className={pageButtonClass} disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} type="button"><ChevronLeft className="size-4" /></button><span>第 {pagination.page} / {Math.max(1, pagination.totalPages)} 页</span><button aria-label="下一页" className={pageButtonClass} disabled={page >= pagination.totalPages} onClick={() => setPage((value) => value + 1)} type="button"><ChevronRight className="size-4" /></button></div></div>; }
function FormField({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="block text-sm"><span className="font-medium">{label}</span><span className="mt-1.5 block">{children}</span>{error ? <span className="mt-1 block text-xs text-danger">{error}</span> : null}</label>; }
function emptyRateDefaults(): RateFormValues { const today = new Date().toISOString().slice(0, 10); return { rateNo: '', polCode: '', polName: '', podCode: '', podName: '', carrierCode: '', serviceName: '', effectiveDate: today, expiryDate: today, etd: '', transitDays: '', supplierName: '', contractNo: '', currency: 'USD', status: 'DRAFT', prices: [{ containerType: '40HQ', costAmount: '', sellAmount: '', currency: 'USD', remark: '' }], charges: [] }; }
function rateDefaults(rate: Rate): RateFormValues { return { rateNo: rate.rateNo, polCode: rate.polCode, polName: rate.polName, podCode: rate.podCode, podName: rate.podName, carrierCode: rate.carrierCode, serviceName: rate.serviceName ?? '', effectiveDate: rate.effectiveDate.slice(0, 10), expiryDate: rate.expiryDate.slice(0, 10), etd: rate.etd ? new Date(rate.etd).toISOString().slice(0, 16) : '', transitDays: rate.transitDays?.toString() ?? '', supplierName: rate.supplierName ?? '', contractNo: rate.contractNo ?? '', currency: rate.currency, status: rate.status, prices: rate.prices.map((price) => ({ containerType: price.containerType, costAmount: price.costAmount, sellAmount: price.sellAmount ?? '', currency: price.currency, remark: price.remark ?? '' })), charges: rate.charges.map((charge) => ({ chargeCode: charge.chargeCode, chargeName: charge.chargeName, chargeBasis: charge.chargeBasis, containerType: charge.containerType ?? '', amount: charge.amount, currency: charge.currency, isIncluded: charge.isIncluded })) }; }
async function requestJson<T>(apiFetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>, input: RequestInfo | URL, init?: RequestInit): Promise<T> { const response = await apiFetch(input, init); const payload = (await response.json().catch(() => undefined)) as T | ApiErrorPayload | undefined; if (!response.ok) { const error = payload as ApiErrorPayload | undefined; throw new RateApiError(error?.message ?? '运价服务暂时不可用，请稍后重试。', error?.code); } return payload as T; }
function toRateError(error: unknown): RateApiError { return error instanceof RateApiError ? error : new RateApiError(error instanceof Error ? error.message : '运价服务暂时不可用，请稍后重试。'); }
function upper(value: string) { return value.trim().toUpperCase(); } function optional(value: string) { return value.trim() || undefined; }
function formatDate(value: string) { return value.slice(0, 10); } function formatMoney(value: string, currency: string) { return `${currency} ${new Intl.NumberFormat('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(value))}`; }
const inputClass = 'h-10 w-full rounded border border-border bg-surface px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15 disabled:cursor-not-allowed disabled:bg-sidebar disabled:text-muted';
const filterClass = 'h-9 min-w-24 rounded border border-border bg-surface px-3 text-sm outline-none focus:border-primary';
const secondaryButton = 'inline-flex h-8 items-center gap-1.5 rounded border border-border px-3 text-sm font-medium hover:border-primary hover:text-primary';
const pageButtonClass = 'grid size-9 place-items-center rounded border border-border disabled:cursor-not-allowed disabled:opacity-40';
